### ISSUE TITLE
格式转换的地方如果没有需要转换的文件，就提示没有文件需要转换吧

### ISSUE THREAD

**Issue by Spencer981120** [kellyiscute/WalkmanManager#7]
**Bug description**
即便没有需要转换的文件，点击转换按钮之后圈圈依然会开始转。

**Expected behavior**
没有需要转换的话可以弹窗说明没有文件需要转换。转换完后也可以弹窗提示一下或者直接关闭窗口也是可以的。

**Screenshot**
![image](https://user-images.githubusercontent.com/36749347/59270936-4c4a7d80-8c85-11e9-9db0-a7b39e42ffd5.png)

**Desktop:**
 - OS & Build: [Windows 10 64bit 18362.145]
 - Version [Beta3]

**Comment by kellyiscute** [comment]
todo

**Comment by kellyiscute** [comment]
bug fixed
