### ISSUE TITLE
同步网易云歌单到本地时如果匹配到的歌曲数量太大，程序会崩溃

### ISSUE THREAD

**Issue by Spencer981120** [kellyiscute/WalkmanManager#8]
**Describe the bug**
同步网易云歌单到本地时如果匹配到的歌曲数量太大，程序会崩溃。数量少的话没有问题

**Desktop (please complete the following information):**
 - OS & Build: [Windows 10 64bit 18362.175]
 - Version [B3]

**Comment by kellyiscute** [comment]
复现步骤？

**Comment by Spencer981120** [comment]
点同步到本地之后匹配过程进行到大概40%（总量219首）到60%（总量1000）的时候就crash了。
第三个歌单只匹配到一首，就没有问题

**Comment by kellyiscute** [comment]
可以把数据库发给我吗

**Comment by Spencer981120** [comment]
[data.zip](https://github.com/guo40020/WalkmanManager/files/3294272/data.zip)

**Comment by kellyiscute** [comment]
bug fixed
