### ISSUE TITLE
歌曲传输过程中底部会不断弹出设备插入/拔出的提示

### ISSUE THREAD

**Issue by Spencer981120** [kellyiscute/WalkmanManager#9]
**Describe the bug**
歌曲传输过程中底部会不断弹出设备插入/拔出的提示

**To Reproduce**
开始传输后就会有
ppt里是视频[演示文稿1.pptx](https://github.com/guo40020/WalkmanManager/files/3316712/1.pptx)
![image](https://user-images.githubusercontent.com/36749347/59962441-0c528880-9518-11e9-89bb-607670a3fd5d.png)

**Desktop (please complete the following information):**
 - OS & Build: [e.g. Windows 10 64bit 18362.175]
 - Version [B4]

**Additional context**

**Comment by kellyiscute** [comment]
Microsoft's fault. **NOT MINE**

**Comment by kellyiscute** [comment]
Actual Reason Unknown
